---
- name: Restart senlin-api container
  vars:
    service_name: "senlin-api"
    service: "{{ senlin_services[service_name] }}"
    senlin_conf: "{{ senlin_confs.results|selectattr('item.key', 'match', 'senlin.conf')|first }}"
    senlin_api_container: "{{ check_senlin_containers.results|selectattr('item.key', 'match', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment:
      DAEMON: "senlin-api"
    restart_policy: "{{ docker_restart_policy }}"
  when: senlin_conf.changed | bool
        or senlin_api_container.changed | bool
        or (senlin_database_migrate is defined and senlin_database_migrate.changed | bool)

- name: Restart senlin-engine container
  vars:
    service_name: "senlin-engine"
    service: "{{ senlin_services[service_name] }}"
    senlin_conf: "{{ senlin_confs.results|selectattr('item.key', 'match', 'senlin.conf')|first }}"
    senlin_engine_container: "{{ check_senlin_containers.results|selectattr('item.key', 'match', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment:
      DAEMON: "senlin-engine"
    restart_policy: "{{ docker_restart_policy }}"
  when: senlin_conf.changed | bool
        or senlin_engine_container.changed | bool
        or (senlin_database_migrate is defined and senlin_database_migrate.changed | bool)
