---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "!*"
      sinks:
          - meter_sink
    - name: cpu_bill_source
      interval: 60
      meters:
          - "cpu"
      sinks:
          - cpu_bill_sink
    - name: memory_bill_source
      interval: 60
      meters:
          - "memory.usage"
      sinks:
          - meter_sink
    - name: disk_bill_source
      interval: 60
      meters:
          - "disk.read.bytes"
          - "disk.read.requests"
          - "disk.write.bytes"
          - "disk.write.requests"
      sinks:
          - disk_bill_sink
    - name: network_bill_source
      interval: 60
      meters:
          - "network.incoming.bytes"
          - "network.incoming.packets"
          - "network.outgoing.bytes"
          - "network.outgoing.packets"
      sinks:
          - network_bill_sink
    - name: bandwidth_bill_source
      interval: 60
      meters:
          - "bandwidth"
      sinks:
          - meter_sink
    - name: instance_source
      interval: 600
      meters:
          - "instance"
          - "instance.flavor"
          - "instance.delete"
          - "instance.scheduled"
      sinks:
          - meter_sink
    - name: memory_source
      interval: 600
      meters:
          - "memory"
      sinks:
          - meter_sink
    - name: image_source
      interval: 600
      meters:
          - "image"
          - "image.size"
          - "image.download"
          - "image.serve"
      sinks:
          - meter_sink
    - name: volume_source
      interval: 600
      meters:
          - "volume"
          - "volume.size"
      sinks:
          - meter_sink
    - name: identity_source
      interval: 600
      meters:
          - "identity.user.*"
          - "identity.group.*"
          - "identity.role.*"
          - "identity.project.*"
          - "identity.trust.*"
      sinks:
          - meter_sink
    - name: network_source
      interval: 600
      meters:
           - "network*"
           - "subnet*"
           - "port*"
           - "router*"
           - "ip*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - notifier://
    - name: cpu_bill_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - notifier://
    - name: disk_bill_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "disk\\.(read|write)\\.(bytes|requests)"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "disk.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
    - name: network_bill_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
