mon_group_name: "obs"
osd_group_name: "obs"
rgw_group_name: "obs"

eayunobs_haproxy_nb: "12"
eayunobs_haproxy_maxconn: "3000"
rgw_civetweb_num_threads: "{{ eayunobs_haproxy_nb|int * eayunobs_haproxy_maxconn|int / groups['obs']|length }}"
