---
packages_needed_on_fuel:
  - python-docker-py

images_directory: "{{ eayunstack_base }}/docker_images"

eayunstack_docker_images:
  registry:
    image_name: "{{ eayunstack_docker_prefix }}/registry"
    file_name: "eayunstack_registry.latest"
    push: "False"
  trove_base:
    image_name: "{{ eayunstack_docker_prefix }}/trove-base"
    file_name: "eayunstack_trove_base.latest"
    push: "True"
  zaqar_server:
    image_name: "{{ eayunstack_docker_prefix }}/zaqar-base"
    file_name: "eayunstack_zaqar_server.latest"
    push: "True"

eayunstack_registry_diretory: "/var/lib/eayunstack-registry"
eayunstack_registry_port: "5010"

eayunstack_registry_check_retries: 5
eayunstack_registry_check_delay: 10
